# Generated by Django 4.1.7 on 2023-06-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='ceiling',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='cloudCover',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='conditions',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='dewPoint',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='icon',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='pressure',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='temperatureApparent',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='uvIndex',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='visibility',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='weatherDescription',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='windGust',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='forecast_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='humidity',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='precipitation',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='wind_direction',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='wind_speed',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
