# Generated by Django 4.1.7 on 2023-07-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_remove_weather_forecast_time_weather_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
