# Generated by Django 4.1.7 on 2023-07-11 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0004_alter_weather_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='time',
        ),
    ]
