# Generated by Django 4.1.7 on 2023-07-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0005_remove_weather_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
