# Generated by Django 4.1.7 on 2023-07-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0006_weather_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
